server:
  port: 10010
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

#Zuul中已经启动了熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
#Zuul的超时处理 ribbon的超时时长，真实值是（read + connect）* 2 必须小于hystrix时长
ribbon:
  ReadTimeout: 500
#请求连接的超时时间
  ConnectTimeout: 2000

#未忽略前缀的设置
#zuul:
#  routes:
#    user-service: /user/**
#  #忽略服务配置
#  ignored-services:
#    - user-service

#去除前缀的设置
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false #忽略前缀
#  prefix: /api #全局前缀
#  strip-prefix: false #忽略全局前缀
#配置网关规则 不配取默认配置 user-service consurmer-service
#zuul:
#  routes:
#    user-service: /user-service/**
#      path: /user-service/**
#      url: http://127.0.0.1:8081
#      serviceId: user-service
