server:
  port: 10010
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

#未忽略前缀的设置
#zuul:
#  routes:
#    user-service: /user/**
#  #忽略服务配置
#  ignored-services:
#    - user-service

#去除前缀的设置
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false #忽略前缀
#  prefix: /api #全局前缀
#  strip-prefix: false #忽略全局前缀
#配置网关规则 不配取默认配置 user-service consurmer-service
#zuul:
#  routes:
#    user-service: /user-service/**
#      path: /user-service/**
#      url: http://127.0.0.1:8081
#      serviceId: user-service
