server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.248/xw_taes
    username: root
    password: freecg
mybatis:
  type-aliases-package: cn.xw.user.pojo